# cf. https://starship.rs/ja-JP/config/#%E3%83%97%E3%83%AD%E3%83%B3%E3%83%97%E3%83%88

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$rust\
$golang\
$python\
$lua\
$nodejs\
$haskell\
$java\
$kotlin\
\n$character"""

# シェルのプロンプトの間に空行を挿入する
add_newline = true

[directory]
# ディレクトリ最大表示階層
truncation_length = 10
# gitルートでパスを省略するか
truncate_to_repo = false
style = 'bold cyan'

[git_branch]
disabled = false
format = '[❯](fg:#a5aab4) [$symbol$branch(:$remote_branch)]($style) '
style = "bold green"

[package]
disabled = false
symbol = "\uF487"
style = "bold purple"
format = '[❯](fg:#a5aab4) [$symbol $version]($style) '

[rust]
disabled = false
style = "bold blue"
symbol = 'Rust'
format = '[❯](fg:#a5aab4) [$symbol ($version )]($style)'

[golang]
disabled = false
symbol = 'Go'
format = '[❯](fg:#a5aab4) [$symbol($version )]($style)'

[python]
disabled = false
symbol = 'Python'
format = '[❯](fg:#a5aab4) [$symbol($version )]($style)'

[lua]
disabled = false
symbol = 'Lua'
format = '[❯](fg:#a5aab4) [$symbol($version )]($style)'

[nodejs]
disabled = false
symbol = 'Node'
format = '[❯](fg:#a5aab4) [$symbol($version )]($style)'

[haskell]
symbol = 'Haskell'
disabled = false
format = '[❯](fg:#a5aab4) [$symbol($version )]($style)'

[java]
disabled = false
symbol = 'Java'
format = '[❯](fg:#a5aab4) [$symbol($version )]($style)'

[kotlin]
disabled = false
symbol = 'Kotlin'
format = '[❯](fg:#a5aab4) [$symbol($version )]($style)'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
